### ISSUE TITLE
Invalid participant IDs in group stages

### ISSUE THREAD

**Issue by OmairMunir0** [stefangeyer/challonge-java#17] opened 2020-07-26 12:49 UTC
Here is how you reproduce it:

- Create a tournament with group stage and a final stage
- Add participants
- Run the method `Challonge.getMatches(tournament, participant)`, where the participant is obtained from `Challonge.getParticipants(tournament)`, you'll get an empty list even if the player has matches in the group stage. However for the final stage, it works.

**Comment by gpluscb** [comment] 2020-08-14 10:54
I believe the problem is on the side of the Challonge API here. From the [api docs](https://api.challonge.com/v1):
>  Please note, two-stage tournaments are not yet supported by our public API. They'll be available in V2 along with 3+ participant per match support.

**Comment by stefangeyer** [comment] 2020-10-14 11:22
Yeah, this seems to be yet another API limitation. Should API results differ from what our wrapper produces, feel free to provide an example.

Closing this issue for now.

**Closed as completed by stefangeyer** 2020-10-14 11:22 UTC
